=== WojciechJ/JJX-2020z/zadanie_1/wydzialy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="wydzialy">
  
  <xs:complexType>
    <xs:sequence>
     <xs:element ref="wydzial" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="wydzial">
    <xs:complexType>
      <xs:sequence>
      <xs:element name="nazwa_wydzial" minOccurs="1" maxOccurs="1" type="xs:string" />
      <!-- wydział posiada nazwę oraz dowolną liczbę adresów -->
      <xs:element name="adres_wydzial" minOccurs="1" maxOccurs="unbounded" />
      <xs:element ref="pracownicy" />
      <xs:element ref="przedmioty" />
      </xs:sequence>	
      <!-- wydział ma unikalne id (xsd:ID) -->
      <xs:attribute name="id"  type="xs:ID" use="required"/>	 
    </xs:complexType> 
  </xs:element>
  
  <xs:element name="pracownicy">
  <!-- Pracowników należy wdrożyć jako typ złożony. -->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pracownik" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <!-- Pracowników należy wdrożyć jako typ złożony. -->
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="pracownik">
  <xs:complexType>
    <xs:sequence>
    <!-- Pracowników należy wdrożyć jako typ złożony. -->
    <!-- Imię i nazwisko pracowników jest obowiązkowe -->
      <xs:element name="imie_pracownik" minOccurs="1" maxOccurs="1" type="xs:string"/>
      <xs:element name="nazwisko_pracownik"  minOccurs="1" maxOccurs="1" type="xs:string"/>
      <!-- tytuł nie jest konieczny -->
      <xs:element name="tytul_pracownik" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
       <!-- Mamy do wyboru 3 kategorie pracowników: „naukowy”, „administracyjny” lub „techniczny”. -->
      <xs:element name="kategoria_pracownik" minOccurs="0" maxOccurs="3">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="naukowy"/>
            <xs:enumeration value="administracyjny"/>
            <xs:enumeration value="techniczny"/>
          </xs:restriction>
        </xs:simpleType>  
      </xs:element>
      <!-- Każdy pracownik posiada adres.  -->
      <!-- Pracownik musi mieć przypisany co najmniej jeden adres. -->
      <xs:element ref="adres" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="id" use="required" type="xs:ID"/>
        <xs:attribute name="idref" type="xs:IDREF" />
    </xs:complexType>
  </xs:element>
  
  <xs:element name="adres">
  <!-- Adres musi być zaimplementowany jako typ złożony. -->
    <xs:complexType>
    <!-- Ulica, numer, kod pocztowy i miejscowość muszą być zapisywane w określonej kolejności. -->
      <xs:sequence>
        <xs:element name="ulica_adres" type="xs:string" />
        <xs:element name="numer_adres" type="xs:integer" />
        <xs:element name="kod_pocztowy_adres">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="6"/>
              <xs:maxLength value="6"/>
              <xs:pattern value="\d{2}-\d{3}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="miejscowosc_adres" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="przedmioty">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="przedmiot" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>	
  </xs:element>
  
  <xs:element name="przedmiot">
  <xs:complexType>
    <xs:all>
    <!-- Ma także nazwę, opis oraz liczbę uczestników. -->
      <xs:element name="nazwa_przedmiot" type="xs:string" />
      <xs:element name="opis_przedmiot" type="xs:string" />
      <!-- Przedmiot będzie nauczany przez co najmniej jednego pracownika -->
      <xs:element name="prowadzacy_przedmiot">
        <xs:complexType>
          <xs:sequence>
            <xs:element ref="prowadzacy" minOccurs="1" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
		
      <xs:element name="studenci">
        <xs:complexType>
          <xs:sequence>
          <!-- Przedmiot będzie anulowany, jeśli zapisze się na niego mniej niż 6 studentów lub więcej niż 400 -->
            <xs:element ref="student" minOccurs="6" maxOccurs="400" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <!-- Każdy przedmiot posiada unikalny kod przedmiotu. -->
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:complexType>
  </xs:element>
 
  <xs:element name="student">
  <xs:complexType>
    <xs:all>
      <xs:element name="imie_student" type="xs:string" />
      <xs:element name="nazwisko_student" type="xs:string" />
      <xs:element name="indeks_student" type="xs:integer" /> 	  
    </xs:all>
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:complexType>
  </xs:element>
  
  <xs:element name="prowadzacy">
  <xs:complexType>
  <!-- Należy zapewnić, że będzie to pracownik już zdefinowany (xsd:IDREF). -->
      <xs:attribute name="idref" use="required" type="xs:IDREF" />
  </xs:complexType>
  </xs:element>
  
</xs:schema>

=== WojciechJ/JJX-2020z/zadanie_1/wydzialy.xml
<?xml version="1.0" encoding="utf-8"?>
<wydzialy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="wydzialy.xsd">
  <wydzial id="wmipoz">
    <nazwa_wydzial>Wydział Matematyki i Informatyki</nazwa_wydzial>
    <adres_wydzial>Porznań</adres_wydzial>
    <adres_wydzial>Morawsko</adres_wydzial>
    <pracownicy id="pracownicy_0">

        <pracownik id="pracownik_0">
            <imie_pracownik>Jan</imie_pracownik>
            <nazwisko_pracownik>Kowalski</nazwisko_pracownik>
            <tytul_pracownik>Profesor</tytul_pracownik>
            <kategoria_pracownik>naukowy</kategoria_pracownik>
            <adres>
                <ulica_adres>Słuchawkowa</ulica_adres>
                <numer_adres>1234</numer_adres>
                <kod_pocztowy_adres>12-123</kod_pocztowy_adres>
                <miejscowosc_adres>Poznań</miejscowosc_adres>
            </adres>
        </pracownik>

        <pracownik id="pracownik_1">
            <imie_pracownik>Maria</imie_pracownik>
            <nazwisko_pracownik>Nowak</nazwisko_pracownik>
            <tytul_pracownik>magister</tytul_pracownik>
            <kategoria_pracownik>administracyjny</kategoria_pracownik>
            <adres>
                <ulica_adres>Mikrofonowa</ulica_adres>
                <numer_adres>4321</numer_adres>
                <kod_pocztowy_adres>12-123</kod_pocztowy_adres>
                <miejscowosc_adres>Poznań</miejscowosc_adres>
            </adres>
        </pracownik>

    </pracownicy>

    <przedmioty>

      <przedmiot id="przedmiot_0">
        <nazwa_przedmiot>Matematyka dyskretna</nazwa_przedmiot>
        <opis_przedmiot>nauka o ...</opis_przedmiot>
        <prowadzacy_przedmiot>
          <prowadzacy idref="pracownik_0" />
        </prowadzacy_przedmiot>
        <studenci>
          <student id="student_0">
            <imie_student>Krystian</imie_student>
            <nazwisko_student>Wkrętarka</nazwisko_student>
            <indeks_student>426140</indeks_student>
          </student>
          <student id="student_1">
            <imie_student>Mariusz</imie_student>
            <nazwisko_student>Śróbokręt</nazwisko_student>
            <indeks_student>426141</indeks_student>
          </student>
          <student id="student_2">
            <imie_student>Monika</imie_student>
            <nazwisko_student>Piła</nazwisko_student>
            <indeks_student>426142</indeks_student>
          </student>
          <student id="student_3">
            <imie_student>Aneta</imie_student>
            <nazwisko_student>Młotek</nazwisko_student>
            <indeks_student>426143</indeks_student>
          </student>
          <student id="student_4">
            <imie_student>Karol</imie_student>
            <nazwisko_student>Wyrzynarka</nazwisko_student>
            <indeks_student>426144</indeks_student>
          </student>
          <student id="student_5">
            <imie_student>Karolina</imie_student>
            <nazwisko_student>Szlifierka</nazwisko_student>
            <indeks_student>426145</indeks_student>
          </student>
        </studenci>
      </przedmiot>

      <przedmiot id="przedmiot_1">
        <nazwa_przedmiot>Pracownia programowania</nazwa_przedmiot>
        <opis_przedmiot>podstawy C</opis_przedmiot>
        <prowadzacy_przedmiot>
          <prowadzacy idref="pracownik_1" />
        </prowadzacy_przedmiot>
        <studenci>
          <student id="student_6">
            <imie_student>Krystian</imie_student>
            <nazwisko_student>Wkrętarka</nazwisko_student>
            <indeks_student>426140</indeks_student>
          </student>
          <student id="student_7">
            <imie_student>Mariusz</imie_student>
            <nazwisko_student>Śróbokręt</nazwisko_student>
            <indeks_student>426141</indeks_student>
          </student>
          <student id="student_8">
            <imie_student>Monika</imie_student>
            <nazwisko_student>Piła</nazwisko_student>
            <indeks_student>426142</indeks_student>
          </student>
          <student id="student_9">
            <imie_student>Aneta</imie_student>
            <nazwisko_student>Młotek</nazwisko_student>
            <indeks_student>426143</indeks_student>
          </student>
          <student id="student_10">
            <imie_student>Karol</imie_student>
            <nazwisko_student>Wyrzynarka</nazwisko_student>
            <indeks_student>426144</indeks_student>
          </student>
          <student id="student_11">
            <imie_student>Karolina</imie_student>
            <nazwisko_student>Szlifierka</nazwisko_student>
            <indeks_student>426145</indeks_student>
          </student>
        </studenci>
      </przedmiot>

    </przedmioty>

  </wydzial>

  <wydzial id="wbpoz">
    <nazwa_wydzial>Wydział Biologii</nazwa_wydzial>
    <adres_wydzial>Porznań</adres_wydzial>
    <adres_wydzial>Morawsko</adres_wydzial>
    <pracownicy id="pracownicy_1">

        <pracownik id="pracownik_2">
            <imie_pracownik>Jan</imie_pracownik>
            <nazwisko_pracownik>Kowalski</nazwisko_pracownik>
            <tytul_pracownik>Profesor</tytul_pracownik>
            <kategoria_pracownik>naukowy</kategoria_pracownik>
            <adres>
                <ulica_adres>Słuchawkowa</ulica_adres>
                <numer_adres>1234</numer_adres>
                <kod_pocztowy_adres>12-123</kod_pocztowy_adres>
                <miejscowosc_adres>Poznań</miejscowosc_adres>
            </adres>
        </pracownik>

        <pracownik id="pracownik_3">
            <imie_pracownik>Maria</imie_pracownik>
            <nazwisko_pracownik>Nowak</nazwisko_pracownik>
            <tytul_pracownik>magister</tytul_pracownik>
            <kategoria_pracownik>administracyjny</kategoria_pracownik>
            <adres>
                <ulica_adres>Mikrofonowa</ulica_adres>
                <numer_adres>4321</numer_adres>
                <kod_pocztowy_adres>12-123</kod_pocztowy_adres>
                <miejscowosc_adres>Poznań</miejscowosc_adres>
            </adres>
        </pracownik>

    </pracownicy>

    <przedmioty>

      <przedmiot id="przedmiot_2">
        <nazwa_przedmiot>Matematyka dyskretna</nazwa_przedmiot>
        <opis_przedmiot>nauka o ...</opis_przedmiot>
        <prowadzacy_przedmiot>
          <prowadzacy idref="pracownik_2" />
        </prowadzacy_przedmiot>
        <studenci>
          <student id="student_12">
            <imie_student>Krystian</imie_student>
            <nazwisko_student>Wkrętarka</nazwisko_student>
            <indeks_student>426140</indeks_student>
          </student>
          <student id="student_13">
            <imie_student>Mariusz</imie_student>
            <nazwisko_student>Śróbokręt</nazwisko_student>
            <indeks_student>426141</indeks_student>
          </student>
          <student id="student_14">
            <imie_student>Monika</imie_student>
            <nazwisko_student>Piła</nazwisko_student>
            <indeks_student>426142</indeks_student>
          </student>
          <student id="student_15">
            <imie_student>Aneta</imie_student>
            <nazwisko_student>Młotek</nazwisko_student>
            <indeks_student>426143</indeks_student>
          </student>
          <student id="student_16">
            <imie_student>Karol</imie_student>
            <nazwisko_student>Wyrzynarka</nazwisko_student>
            <indeks_student>426144</indeks_student>
          </student>
          <student id="student_17">
            <imie_student>Karolina</imie_student>
            <nazwisko_student>Szlifierka</nazwisko_student>
            <indeks_student>426145</indeks_student>
          </student>
        </studenci>
      </przedmiot>

      <przedmiot id="przedmiot_3">
        <nazwa_przedmiot>Pracownia programowania</nazwa_przedmiot>
        <opis_przedmiot>podstawy C</opis_przedmiot>
        <prowadzacy_przedmiot>
          <prowadzacy idref="pracownik_3" />
        </prowadzacy_przedmiot>
        <studenci>
          <student id="student_18">
            <imie_student>Krystian</imie_student>
            <nazwisko_student>Wkrętarka</nazwisko_student>
            <indeks_student>426140</indeks_student>
          </student>
          <student id="student_19">
            <imie_student>Mariusz</imie_student>
            <nazwisko_student>Śróbokręt</nazwisko_student>
            <indeks_student>426141</indeks_student>
          </student>
          <student id="student_20">
            <imie_student>Monika</imie_student>
            <nazwisko_student>Piła</nazwisko_student>
            <indeks_student>426142</indeks_student>
          </student>
          <student id="student_21">
            <imie_student>Aneta</imie_student>
            <nazwisko_student>Młotek</nazwisko_student>
            <indeks_student>426143</indeks_student>
          </student>
          <student id="student_22">
            <imie_student>Karol</imie_student>
            <nazwisko_student>Wyrzynarka</nazwisko_student>
            <indeks_student>426144</indeks_student>
          </student>
          <student id="student_23">
            <imie_student>Karolina</imie_student>
            <nazwisko_student>Szlifierka</nazwisko_student>
            <indeks_student>426145</indeks_student>
          </student>
        </studenci>
      </przedmiot>

    </przedmioty>

  </wydzial>
</wydzialy>
